name: halide
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - halide==19.0.0
    - -e ../pyviewer

# conda env create -f environment.yml
# conda env update -f environment.yml